var _its = [
    "animal-fondling",
    "annoying",
    "artist formally known as",
    "badly drawn",
    "bald",
    "bastardized",
    "bearded",
    "bloated",
    "bloody",
    "blooming",
    "bottled",
    "broadfaced",
    "bum-banging",
    "cock wielding",
    "cocking",
    "cockmunching",
    "complete",
    "constipated",
    "cross-eyed",
    "cunt rotting",
    "cunting",
    "dandy",
    "dangling",
    "dementing",
    "demonizing",
    "diaper-wearing",
    "dickless",
    "dipping",
    "dipping",
    "dried out",
    "dripping",
    "dumb",
    "enormous",
    "eye-less",
    "failed",
    "failed",
    "fat",
    "fingerlicking",
    "flip-flopping",
    "flipping",
    "friend of a",
    "frigging",
    "fritzl-admiring",
    "fuckfaced",
    "fucking",
    "funky",
    "gag sacking",
    "gigantic",
    "glistering",
    "glorious",
    "go suck a",
    "gold-digging",
    "guzzling",
    "hairy",
    "hard-rubbing",
    "hitler's personal",
    "holy",
    "horse-loving",
    "inbred",
    "indeterminable",
    "instant",
    "irredeemable",
    "irrelevant",
    "leaking",
    "leg-humping",
    "lonely",
    "long-titted",
    "maiming",
    "mental",
    "mong loving",
    "naked",
    "one-balled",
    "overrated",
    "pigfaced",
    "probing",
    "prodigal",
    "pulsating",
    "racist",
    "raging",
    "rambling",
    "ranting",
    "rectal",
    "retarded",
    "rotating",
    "rotting",
    "scruffy-looking",
    "scurvy looking",
    "senile",
    "shitting",
    "silly",
    "slapping",
    "slutty",
    "sodding",
    "sodding",
    "son of a",
    "spastic",
    "spitting",
    "sponglicking",
    "spotty",
    "spunking",
    "stale",
    "sticky",
    "stillborn",
    "stinky",
    "strangely shaped",
    "throbbing",
    "titless",
    "tossing",
    "treacherous",
    "trout-faced",
    "twin-headed",
    "twittering",
    "twunting",
    "unborn",
    "undead",
    "unhuman",
    "unimaginable",
    "utter",
    "virgin",
    "wanking",
    "wanktastic",
    "whoring",
    "wrinkled old"
]

var _is = [
    "anus",
    "arse",
    "ass",
    "asswad",
    "bukake",
    "bum",
    "bunghole",
    "butt",
    "chesticle",
    "clusterfuck",
    "cock",
    "cock-tip",
    "cocksplurt",
    "cockstorm",
    "cockthistle",
    "colon",
    "crap",
    "cum",
    "cunt",
    "dick",
    "dickwhistle",
    "dipstick",
    "douchewaffle",
    "earwax",
    "fart",
    "food trough",
    "fuck",
    "fuckwit",
    "fudge",
    "gaylord",
    "ginger",
    "gloryhole",
    "jizz",
    "lard",
    "llama",
    "nerf",
    "nipple",
    "nut",
    "nutsack",
    "piss",
    "poop",
    "puke",
    "retard",
    "scrotum",
    "semen",
    "shaft",
    "shit",
    "shitehawk",
    "shitface",
    "shitshark",
    "slut",
    "spazz",
    "sperm",
    "sphincter",
    "spunk",
    "suck",
    "tea-bag",
    "tit",
    "tramp",
    "turd",
    "vomit",
    "wank"
]

var _thing = [
    "alien",
    "badger",
    "bait",
    "balls",
    "bandit",
    "barrel",
    "bint",
    "biscuit",
    "bogle",
    "bollock",
    "bottom",
    "boy",
    "bucket",
    "candle",
    "cockroach",
    "diarrhea",
    "dog",
    "erection",
    "excrement",
    "faggot",
    "flaps",
    "foot",
    "force",
    "goatse",
    "handle",
    "head",
    "hole",
    "hole",
    "infidel",
    "jockey",
    "kid",
    "king",
    "knob",
    "lord",
    "lorry",
    "mange",
    "MILF",
    "minge",
    "mong",
    "nugget",
    "pig",
    "pile",
    "pipe",
    "pirate",
    "rag",
    "sack",
    "sample",
    "sock",
    "sod",
    "spack",
    "spunk-bubble",
    "stack",
    "stain",
    "testicle",
    "torch",
    "trailer",
    "tranny",
    "twat",
    "twunt",
    "udder",
    "waffle",
    "wagon",
    "whale",
    "wipe",
    "worm",
    "zombie"
]

var _isAlso = [
    "amputee",
    "basher",
    "bastard",
    "bender",
    "blender",
    "butler",
    "dictator",
    "experiment",
    "extractor",
    "fan",
    "felcher",
    "fondler",
    "fucker",
    "graduate",
    "handler",
    "herder",
    "jacker",
    "licker",
    "lover",
    "packer",
    "piper",
    "plonker",
    "professor",
    "raper",
    "rider",
    "shiner",
    "slapper",
    "sucker",
    "voyeur",
    "wanker",
    "wiper"
]

var combinations = [
    [_its, _is, _thing],
    [_its, _is, _isAlso],
    [_its, _thing, _isAlso],
    [_is, _thing],
    [_is, _isAlso],
    [_thing, _isAlso],
    [_its, _is, _thing, _isAlso]
];

var nl_its = [
    "achterlijke",
    "afgetobde",
    "afvallige",
    "anaalgeboren",
    "bevallige",
    "bevlekte",
    "blaffende",
    "boliviaanse",
    "daadkrachtige",
    "domme",
    "doodgeboren",
    "door de stront getrokken",
    "droogneukende",
    "enorme",
    "enorme",
    "fantastische",
    "gare",
    "gekrompen",
    "gesmolten",
    "glijdende",
    "groengele",
    "homofiele",
    "homopatische",
    "huichelachtige",
    "huigruikende",
    "huigstotende",
    "idiote",
    "in de reet geneukte",
    "in het ootje genomen",
    "ingedaalde",
    "irritante",
    "klontkakkende",
    "kontneukende",
    "kontstarende",
    "kontvingerende",
    "krentkijkende",
    "laffe",
    "leugenachtige",
    "liplikkende",
    "maffe",
    "malle",
    "minimale",
    "natte",
    "niet te versmaden",
    "nozele",
    "omhooggevallen",
    "onbespoten",
    "onnozele",
    "ontzettende",
    "onvervalste",
    "opgebruikte",
    "pedofiele",
    "puisterige",
    "rondruisende",
    "schele",
    "schilferige",
    "sleufvrezende",
    "slingerschijtende",
    "slobberende",
    "snuivende",
    "sproeipoepende",
    "spuitende",
    "stiekeme",
    "takke",
    "uit de naad ruikende",
    "uitgekakte",
    "uitgewoonde",
    "van achteren genomen",
    "verlichte",
    "vertyfde",
    "vieze vuile",
    "vieze",
    "voezelige",
    "voorhuidknabbelende",
    "vooruitgestoken",
    "vuile",
    "vuistneukende",
    "vunzige",
    "zwakzinnige",
    "zwartgeblakerde",
    "zwetende"
]

var nl_its_2 = [
    "aars",
    "anus",
    "bef",
    "billen",
    "blubber",
    "bluf",
    "braak",
    "darm",
    "drollen",
    "endeldarm",
    "fluit",
    "geiten",
    "genots",
    "gier",
    "graf",
    "hasj",
    "hitler",
    "huig",
    "kloot",
    "kluif",
    "kots",
    "kut",
    "pik",
    "pokke",
    "pseudo",
    "riool",
    "rug",
    "ruk",
    "smegma",
    "spuit",
    "staaf",
    "stink",
    "stront",
    "tering",
    "tering",
    "tokus",
    "tyfus",
    "zaad"
]

var nl_thing = [
    "aap",
    "baard",
    "balzak",
    "banaan",
    "batser",
    "baviaan",
    "bewoner",
    "debiel",
    "dwaas",
    "eikel",
    "figuur",
    "flamoes",
    "freak",
    "geit",
    "gladiool",
    "gleuf",
    "haas",
    "hoer",
    "hond",
    "knobbel",
    "laaf",
    "lul",
    "minion",
    "mof",
    "mongool",
    "muppet",
    "nicht",
    "pannekoek",
    "penis",
    "piemel",
    "piemel",
    "pik",
    "puist",
    "pukkel",
    "ridder",
    "rosbief",
    "scheet",
    "scrotum",
    "slet",
    "snol",
    "snor",
    "swaffelaar",
    "tekkel",
    "toerist",
    "toompje",
    "trechter",
    "trechter",
    "uitbater",
    "vergiet",
    "vlek",
    "wijf",
    "zak"
]

var nl_poff = [
    "aarsgarnaal",
    "aasgier",
    "anaalgeneraal",
    "anaalridder",
    "anusacrobaat",
    "anuspiraat",
    "anusridder",
    "augurklul",
    "baardaap",
    "bafkoning",
    "bananenbeffer",
    "befbanaan",
    "befman",
    "beschuitlul",
    "biggebeffer",
    "billepik",
    "bilnaad",
    "bilridder",
    "boerenkut",
    "boerenlul",
    "bokkenlul",
    "bosaap",
    "bosmongool",
    "braakhut",
    "bruinridder",
    "bruinwerker",
    "budhond",
    "dakhaas",
    "darmknikker",
    "darmtoerist",
    "dildotrekker",
    "eikelbijter",
    "eikelkluiver",
    "emmerkut",
    "flamoesfetisjist",
    "flapdrol",
    "geitenbeffer",
    "genotsflikker",
    "gierkut",
    "gleufdoos",
    "gleufgraver",
    "gleuvenlikker",
    "grafbak",
    "grafkop",
    "graftak",
    "hachelknook",
    "hark",
    "heggeneuker",
    "hoer",
    "hoerenloper",
    "homofiel",
    "huppelkut",
    "kamelenpijper",
    "kannezeiker",
    "kebabflap",
    "keuteldeuker",
    "klapperkut",
    "kloothommel",
    "klootviool",
    "klootzak",
    "klotenklapper",
    "knevelkut",
    "koeienkut",
    "koekwous",
    "kontbonker",
    "kontenketser",
    "konthaarkorrel",
    "kontkruimel",
    "kontridder",
    "kopkluiver",
    "kutfrikandel",
    "kuttekop",
    "kuttenlikker",
    "kutveger",
    "kutzwabber",
    "lijkenneuker",
    "makaak",
    "malloot",
    "matennnaaier",
    "moederbatser",
    "moederneuker",
    "neukfout",
    "neukstengel",
    "okselhaas",
    "olifantenlul",
    "paardebeffer",
    "paardenlul",
    "pennelikker",
    "pijpbek",
    "pijpgeit",
    "piklikker",
    "pikvinger",
    "pindapijper",
    "pislul",
    "pisvinger",
    "pisvlek",
    "plakhond",
    "plofkip",
    "plofkop",
    "plofkut",
    "poepchinees",
    "reteneuker",
    "rioolkop",
    "ritsruiker",
    "rosbiefnaaier",
    "rugklimmer",
    "rugkoning",
    "rugtuffer",
    "rukhond",
    "rukpik",
    "schaamluis",
    "schapenkut",
    "schijndode",
    "schijtbek",
    "schijtzak",
    "schimmelteen",
    "schurftkut",
    "slettebak",
    "slootkloot",
    "smetvlek",
    "snotsnuiver",
    "speknek",
    "spermaspuiter",
    "stierenpijper",
    "strontstamper",
    "takketrol",
    "tepeltrut",
    "tietenlokker",
    "tokuslikker",
    "trekvlek",
    "vaderneuker",
    "varkenskop",
    "vaselinevriend",
    "vetvlek",
    "volkorenkut",
    "zaaddonor",
    "zaadslikker",
    "zweetreet",
    "zwijn"
]

var nl_isAlso = [
    "baffer",
    "beffer",
    "bijter",
    "collega",
    "droogneuker",
    "graver",
    "hufter",
    "huichelaar",
    "klopper",
    "kluiver",
    "likker",
    "lurker",
    "maat",
    "naaier",
    "naaier",
    "propper",
    "simulator",
    "slurper",
    "smachter",
    "snuiver",
    "stroper",
    "swaffelaar",
    "trekker",
    "veger",
    "verkrachter",
    "vriend",
    "wipper",
    "zuiger"
]

var nl_combinations = [
    [nl_its, nl_poff],
    [nl_its, nl_its_2, nl_thing],
    [nl_its_2, nl_thing],
    [nl_its, nl_its_2, nl_isAlso],
    [nl_poff]
];

var signs = ["!", ".", ""]

var RandomItem = function(a) {
    return a[Math.floor(Math.random() * a.length)]
}

var FoulGenerate = function(bundle) {
    bundle = bundle || [combinations, nl_combinations]
    var c = RandomItem(bundle) // random combination language bundle
    var words = []
    var rc = RandomItem(c) // random combination
    console.log('rc:', rc)
    for (var i in rc) {
        var rw = RandomItem(rc[i]) // random word
        words.push(rw)
    }
    var rs = RandomItem(signs) // random sign
    return words.join(' ') + rs
}

String.prototype.capitalize = function() {
    return this.charAt(0).toUpperCase() + this.slice(1);
}



var db = require('./lib/listdb').getDB('fouls');

var request = require('request'),
    entities = require('./lib/entities'),
    fs = require('fs');

var showHelp = function(replyTo){
    irc.privmsg(replyTo, "en:~foul nl:~vies,~vuil en/nl:~foil | generating foulness " + FoulGenerate([combinations]) + " | Original generator from: http://foulomatic.hnldesign.nl/"); // typo for buz z ;P
}

listen(regexFactory.startsWith(["vuil", "vies"]), function(match, data, replyTo, from) {
    var words = match[1];
    words = words.trim()
    if (words === 'help') {
        showHelp(replyTo)
        return;
    } else {
        var text = String(words)
        text = text ? text + ' = ' : ""
        text = text + FoulGenerate([nl_combinations])
        text = text.capitalize();
        if (!db.hasValue(text)) db.add(text);
        irc.privmsg(replyTo, text)
        irc.privmsg('NURDbot', '!espreek ' + say);
    }
})

listen(regexFactory.startsWith(["foul"]), function(match, data, replyTo, from) {
    var words = match[1];
    words = words.trim()
    if (words === 'help') {
        showHelp(replyTo)
        return;
    } else {
        var text = String(words)
        text = text ? text + ' = ' : ""
        text = FoulGenerate([combinations])
        text = text.capitalize();
        if (!db.hasValue(text)) db.add(text);
        irc.privmsg(replyTo, text)
        irc.privmsg('NURDbot', '!espeak ' + say);
    }
})

listen(regexFactory.startsWith(["foil"]), function(match, data, replyTo, from) {
    var words = match[1];
    words = words.trim()
    if (words === 'help') {
        showHelp(replyTo)
        return;
    } else {
        var nl = parseInt(Math.round(Math.random()))
        var text = String(words)
        text = text ? text + ' = ' : ""
        if (nl)
            text = FoulGenerate([combinations])
        else
            text = FoulGenerate([nl_combinations])
        
        text = text.capitalize();
        if (!db.hasValue(text)) db.add(text);
        irc.privmsg(replyTo, text)
        if (nl)
            irc.privmsg('NURDbot', '!espreek ' + text);
        else
            irc.privmsg('NURDbot', '!espeak ' + text);
    }
})