// (c) 2012 Richard Carter
// This code is licensed under the MIT license; see LICENSE.txt for details.

// This script handles the following functions:
//     slogan - make a slogan from an input


var db = require('./lib/listdb').getDB('pro');

var listOfSlogans = [
  "151 Countries, One ____",
  "3-in-1 Protection for your ____",
  "8 out of 10 Owners who Expressed a Preference said Their Cats Preferred ____",
  "A Day Without ____ is Like a Day Without Sunshine",
  "A Different Kind Of Company. A Different Kind Of ____",
  "A Finger of ____ is Just Enough to Give Your Kids a Treat",
  "A Glass and a Half in Every ____",
  "A Smooth-Running ____ is a Relaxing Experience",
  "A Taste For ____",
  "A Tough ____ to Follow",
  "A ____ A Day Helps You Work, Rest and Play",
  "A ____ Is Forever",
  "A ____ Works Wonders",
  "A ____ a Day Keeps the Doctor Away",
  "A ____ can Change your Life",
  "A ____'s Too Wet Without One",
  "Aaahh, ____",
  "Absolut ____",
  "All The ____ That's Fit To Print",
  "All You Add Is ____",
  "All You Need is a ____ and a Dream",
  "All ____, All The Time",
  "Always After Me ____",
  "Always ____",
  "America Lives In ____",
  "America's Most Trusted ____",
  "An Army of ____",
  "And All Because The Lady Loves ____",
  "Any Time, Any Place, ____",
  "Are You A ____ Case?",
  "Are You Hungry For ____ Now?",
  "Ask the Man From the ____",
  "Australians Wouldn't Give A ____ For Anything Else",
  "Avez-Vous Un ____",
  "Be Like Dad, Keep ____",
  "Be Young, Have Fun, Drink ____",
  "Beanz Meanz ____",
  "Because I'm Worth ____",
  "Because So Much Is Riding On Your ____",
  "Because ____ Can't Drive",
  "Because ____ is Complicated Enough.",
  "Behold the Power of ____",
  "Bet You Can't Eat ____",
  "Better Ingredients, Better ____",
  "Better Living Through ____",
  "Beware of Expensive ____",
  "Big Chocolate ____",
  "Biting the Hand that Feeds ____",
  "Bread Wi' ____ Taken Out",
  "Break Me Off a Piece of That ____",
  "Bridge That Gap with ____",
  "Bring Out The ____",
  "Builds Bonny ____",
  "Built ____ Tough",
  "But I'd Rather Have a Bowl of ____",
  "Can You Tell ____ From Butter",
  "Can't Do It In Real Life? Do It On ____",
  "Central Heating for ____",
  "Ch, Ch, Ch, Ch, ____",
  "Challenge ____",
  "Change Your Whole ____",
  "Chocolate ____ Since 1911",
  "Choosy Mothers Choose ____",
  "Cleans Right Round The ____",
  "Cleans Your Floor Without ____",
  "Cleans a Big, Big ____ For Less Than Half a Crown",
  "Clunk Click, Every ____",
  "Come Fly The Friendly ____",
  "Come Home To ____",
  "Come One, Come All To ____",
  "Come See the Softer Side of ____",
  "Come to Life.  Come to ____",
  "Come to ____, and Let's Get It Done",
  "Cooks Who Know Trust ____",
  "Crunch All You Want. We'll Make ____",
  "Cuts ____ Time in Half",
  "Daddy or ____",
  "Designed for ____",
  "Designed for ____, Engineered to Last",
  "Devon Knows How They Make ____ So Creamy",
  "Dial Down the ____",
  "Did Somebody Say ____",
  "Ding-Dong! ____ Calling",
  "Discover the ____ Difference",
  "Do Me A Favour... Plug Me Into A ____",
  "Do The ____",
  "Do You Eat The ____ Last",
  "Do You Have The ____ Inside",
  "Do You, uh, ____",
  "Does She or Doesn't She? Only Her ____ Knows for Sure",
  "Does You Does, or Does You Don't Take ____",
  "Does the Hard ____ for You",
  "Does the Hard ____, So You Don't Have To",
  "Doesn't Your Dog Deserve ____?",
  "Doing It Right Before Your ____",
  "Don't Be Vague. Ask for ____",
  "Don't Forget The ____, Mum",
  "Don't Get Mad, Get ____",
  "Don't Hold ____ Back",
  "Don't Just Book It, ____ It",
  "Don't Leave Home Without ____",
  "Don't Live a Little, Live a ____",
  "Don't Say Brown, Say ____",
  "Don't Shop For It, ____ It",
  "Don't You Just Love Being In ____",
  "Don't be an Amber ____",
  "Double the Pleasure, Double the ____",
  "Drink ____, It's The Best!",
  "Drinka Pinta ____ A Day",
  "Driven by ____",
  "Dude, You're Getting a ____",
  "Easy, Breezy, Beautiful ____",
  "Every Bubble's Passed Its ____",
  "Every Kiss Begins With ____",
  "Every ____ Helps",
  "Everyone's Favourite ____",
  "Everything We Do is Driven by ____",
  "Exceedingly Good ____",
  "Fall Into The ____",
  "Fast ____ and Good for You",
  "Feel The Raw Naked ____ Of The Road",
  "Feel the ____",
  "Fill It To The Rim With ____",
  "Fit ____ And Be Satisfied",
  "Flick Your ____",
  "For Mash, Get ____",
  "For That Deep Down Body ____",
  "For The ____ You Don't Yet Know",
  "For a Hard-Earned Thirst, ____",
  "Four out of Five Dentists Recommend ____",
  "Fresh from the Captain's ____",
  "Freshen Up With ____",
  "From Our ____ to Yours",
  "Full Of Eastern ____",
  "Gee, Your ____ Smells Terrific",
  "Get Back Your 'Ooo' With ____",
  "Get Busy with the ____",
  "Get In My ____",
  "Get More From ____",
  "Get Serious. Get ____",
  "Get The ____ Out",
  "Get ____ or Get Out",
  "Get the Door - It's ____",
  "Get the ____ Habit",
  "Give That Man A ____",
  "Give the Dog a ____",
  "Gives A Meal ____-Appeal",
  "Go Crack a ____",
  "Go On, Get Your ____ Out",
  "Go To Work On A ____",
  "Gobble ____",
  "Gonna Be a While? Grab a ____",
  "Good Honest ____ Since 1896",
  "Good Things Happen When ____ Comes To Town",
  "Good To The Last ____",
  "Good ____ Has Danish Written All Over It",
  "Good to the Last ____",
  "Got To Get To ____",
  "Got ____",
  "Got a ____? You're in Luck",
  "Gotta Lotta ____",
  "Grab Life by the ____",
  "Great ____. Great Times",
  "Half the ____, All the Taste",
  "Hand-Built by ____",
  "Hands That Do Dishes Can Be Soft As Your ____",
  "Happiness is ____-Shaped",
  "Happiness is a Cigar Called ____",
  "Have You Forgotten How Good ____ Tastes",
  "Have You Had Your ____ Today",
  "Have You ____ Today?",
  "Have ____ Your Way",
  "Have a Break. Have a ____",
  "Have a ____ and Smile",
  "He Who Thinks ____ Drinks ____",
  "Ho Ho Ho, Green ____",
  "Hope It's ____, It's ____, We Hope It's ____..",
  "How Do You Eat <U>Your</U> ____",
  "How Many Licks Does it Take to Get to the Center of a ____",
  "How Refreshing! How ____",
  "Hungry? Why Wait? Grab a ____",
  "I Bet He Drinks ____",
  "I Can't Believe I Ate The Whole ____",
  "I Can't Believe It's Not ____",
  "I Feel Like ____ Tonight",
  "I Learned It By Watching ____",
  "I Like the ____ in You",
  "I Liked The ____ So Much, I Bought The Company",
  "I Love What You Do For ____",
  "I Saw ____ and I Thought of You",
  "I Scream, You Scream, We All Scream for ____",
  "I Think, Therefore ____",
  "I Want My ____",
  "I Was a ____ Weakling",
  "I Wish I Were a ____ Weiner",
  "I Wish They All Could Be ____ Girls",
  "I am Stuck on ____, 'Cause ____'s Stuck on Me",
  "I'd Like to Buy the World a ____",
  "I'd Love A ____",
  "I'd Walk a Mile for a ____",
  "I'm Cuckoo For ____",
  "I'm Lovin' ____",
  "I'm Not Gonna Pay A Lot For This ____",
  "I'm Only Here For The ____",
  "I'm a Secret ____ Drinker",
  "I'm not Just the ____, I'm a Member",
  "I've Seen The Future, and It's ____-Shaped",
  "If Only Everything in Life was as Reliable as a ____",
  "If You Can't Beat ____, Join ____",
  "If You Like A Lot Of ____ On Your Biscuit, Join Our Club",
  "If You Like A Lot of Chocolate on Your ____, Join Our Club",
  "If You Really Want To Know, Look In The ____",
  "If You Want To Get Ahead, Get A ____",
  "If You've Got the Time, We've Got the ____",
  "Is It Live, Or Is It ____",
  "Is ____ In You",
  "It Could Be ____",
  "It Does Exactly What It Says On The ____",
  "It Makes Your ____ Smack",
  "It Must Be ____",
  "It Needn't Be Hell With ____",
  "It Takes A Tough Man To Make A Tender ____",
  "It Takes Two Hands To Hold A ____",
  "It's <U>Different</U> in a ____",
  "It's A Bit Of A ____",
  "It's Good To Talk ____",
  "It's Got To Be ____",
  "It's How ____ Is Done",
  "It's Just For Me And My ____",
  "It's Not All ____, ____, ____, you know",
  "It's Not TV. It's ____",
  "It's Shake 'n' ____, and I Helped",
  "It's Slightly Rippled with a Flat ____",
  "It's That ____ Feeling.",
  "It's ____ Time",
  "It's a Beautiful ____",
  "It's a Lot Less ____ Than a Hover",
  "It's a New ____ Every Day",
  "It's a ____ Adventure",
  "It's the Bright One, it's the Right One, that's ____",
  "It's the ____ Fizz That Does The Bizz",
  "It's the ____ You Can See",
  "Just Do ____",
  "Just Like ____ Used To Make",
  "Just One ____ - Give It To Me",
  "Just What The ____ Ordered",
  "Just for the Taste of ____",
  "Keep That ____ Complexion",
  "Kids Will Do Anything For ____",
  "Kills All Known ____ - Dead",
  "Leave the ____ to Us",
  "Leaves Your ____ Minty not Mediciney",
  "Leggo my ____",
  "Let The ____ Take The Strain",
  "Let Your Fingers Do the Walking Through the ____",
  "Let Your ____ Do The Walking",
  "Let the ____ Begin",
  "Let's Face The Music and ____",
  "Life Should Taste As Good As ____",
  "Life's Pretty Straight Without ____",
  "Lightening the ____",
  "Like ____. Like Never Before",
  "Lipsmackin' Thirstquenchin' Acetastin' Motivatin' Goodbuzzin' Cooltalkin' Highwalkin' Fastlivin' Evergivin' Coolfizzin' ____",
  "Little. Yellow. Different. ____",
  "Live in Your ____, Play in Ours",
  "Look For The ____ Label",
  "Look, Ma, No ____",
  "Loves the ____ You Hate",
  "Made In Scotland From ____",
  "Made To Make Your ____ Water",
  "Made in Scotland from ____",
  "Make Every ____ Count",
  "Make Fun of ____",
  "Make It A ____ Night",
  "Make Room for the ____",
  "Make Someone Happy with a ____",
  "Make ____ Yours",
  "Make the Most of ____",
  "Makes You Feel ____ Again",
  "Making ____ Taste Better",
  "Mama's got the Magic of ____",
  "Mamma Mia, That'sa Spicy ____",
  "Marvin the Mountie Always Gets His ____",
  "Maybe She's Born With It, Maybe It's ____",
  "Melts In Your ____, Not In Your Hand",
  "Men Can't Help Acting On ____",
  "Mild Green ____ Liquid",
  "Moms Like You Choose ____",
  "Monsieur, with this ____ you are really spoiling us",
  "More Than Just a ____",
  "More ____ Please",
  "Moving at the Speed of ____",
  "Mum's Gone to ____",
  "My Anti-Drug is ____",
  "My Doctor Says '____'",
  "My Goodness, My ____",
  "My ____",
  "My ____ to Yours",
  "Naughty, but ____",
  "Never Knowingly ____",
  "New Thinking. New ____",
  "Next to the Breast, ____'s the Best",
  "No ____, No Comment",
  "No-One Does Chicken Like ____",
  "Nobody Better Lay a Finger on my ____",
  "Nobody Can Do It Like ____ Can",
  "Nobody Does It Like ____",
  "Not Just Nearly ____, But Really ____",
  "Nothin' Says Lovin' Like ____ from the Oven",
  "Nothing Acts Faster Than ____",
  "Nothing Comes Between Me And My ____",
  "Nothing Runs Like A ____",
  "Nothing Sucks Like A ____",
  "Nothing Works Better Than a ____",
  "Now with 50% more ____",
  "Obey Your ____",
  "Oh Hungry? Oh ____",
  "Once Driven, Forever ____",
  "Once You Go ____, You'll Never Go Back",
  "Once You Pop, You Can't Stop ____",
  "Only The Crumbliest Flakiest ____.",
  "Only ____ Can Prevent Forest Fires",
  "Only ____ Has The Answer",
  "Only a Fool Breaks the ____",
  "Out Of The Strong Came Forth ____",
  "P-P-P-Pick Up A ____",
  "Pardon Me, Do You Have Any Grey ____",
  "Please Don't Squeeze The ____",
  "Pleasing ____ the World Over",
  "Plink, Plink, ____..",
  "Plop, Plop, Fizz, Fizz, Oh, What a ____ it is",
  "Poppin' Fresh ____",
  "Power For Your ____",
  "Prepare To Want ____",
  "Pride of the ____ For Over a Hundred Years",
  "Probably The Best ____ In The World",
  "Prolongs Active ____",
  "Promise Her Anything, But Give Her ____",
  "Pure ____",
  "Put A ____ In Your Tank",
  "Puts the ____ in Britain",
  "Race for the ____",
  "Reach Out and Touch ____",
  "Reach for the ____",
  "Recommended By Dr. ____",
  "Refreshes the ____ Other Beers Cannot Reach",
  "Ribbed For Her ____",
  "Ring Around the ____ Gets Your Whole Wash Clean",
  "Run For The ____",
  "Savour the Flavour of ____",
  "Say It With ____",
  "Schhh... You Know ____",
  "See the Face You Love Light Up With ____",
  "See the USA in Your ____",
  "See the ____, Feel the Shine",
  "Semper ____",
  "Shake the Bottle, Wake the ____",
  "Sharing the ____ of your Life",
  "Show Me The ____",
  "Silly Rabbit, ____ is for Kids",
  "Simple Impartial ____",
  "Smart. Beautiful. ____",
  "Snap Into A Slim ____",
  "Snap into a ____",
  "Snap! Crackle! ____",
  "So Easy, No Wonder ____ is #1",
  "Solutions For a Small ____",
  "Something Special In The ____",
  "Sometimes You Feel Like a ____, Sometimes You Don't",
  "Splash ____ All Over",
  "Spreads Straight from the ____",
  "Step Into The ____",
  "Stimulation for Body and ____",
  "Stop! This ____ is not Ready Yet",
  "Stop. Go. ____",
  "Strong Enough for a Man, Made for a ____",
  "Strong and Beautiful, Just Like ____",
  "Super ____ is Almost Here",
  "Sweet as the Moment When the ____ Went ",
  "Take Two Bottles into the ____",
  "Take ____",
  "Takes a ____ but it Keeps on Tickin'",
  "Taste the ____",
  "Tastes Great, Less ____",
  "Tell Them About The ____, Mummy",
  "Tense, Nervous, ____",
  "Thank ____ It's Friday",
  "That'll be the ____",
  "That's Handy, Harry! Stick It In The ____",
  "The Appliance of ____",
  "The Best Part of Waking Up is ____ in Your Cup",
  "The Best ____ A Man Can Get",
  "The Best ____ Under One Roof",
  "The Better Way to Start the ____",
  "The Biggest ____ Pennies Can Buy",
  "The Cookie That Thinks It's a ____",
  "The Coolest ____ on Ice",
  "The Cream of ____",
  "The Curiously Strong ____",
  "The Dirt says Hot, The Label says ____",
  "The Future's Bright. The Future's ____",
  "The Good ____ Kids Go For",
  "The Home of ____",
  "The Incredible, Edible ____",
  "The Joy of ____",
  "The Lighter Way To Enjoy ____",
  "The Lion Goes from ____ to ____",
  "The Loudest Noise Comes From The Electric ____",
  "The Man From ____, he says ",
  "The Most Interesting ____ in the World",
  "The Non-Sticky Sticky ____",
  "The Passionate Pursuit of ____",
  "The Queen of ____",
  "The Real Smell of ____",
  "The Right ____ at the Right Time",
  "The Science Of ____",
  "The Sweet You Can Eat Between Meals Without Ruining Your ____",
  "The Sweet You Can't Eat Without ____",
  "The Too Good to Hurry ____",
  "The Ultimate ____ Machine",
  "The Way A ____ Should Be",
  "The World's Favourite ____",
  "The World's Local ____",
  "The World's ____ Marketplace",
  "The ____ Bars Are On Me",
  "The ____ Breakfast",
  "The ____ Drinker's Lighter ____",
  "The ____ Effect",
  "The ____ For All Ages",
  "The ____ Goes Straight to your Head",
  "The ____ Of A New Generation",
  "The ____ Of Paradise",
  "The ____ Side Of Life",
  "The ____ Sign Means Happy Motoring",
  "The ____ That Eats Like A Meal",
  "The ____ That Likes To Say Yes",
  "The ____ That Refreshes",
  "The ____ With The Hole",
  "The ____ is Mightier than the Sword",
  "The ____ of Champions",
  "The ____ of Confidence",
  "The ____ of your Life",
  "The ____ that Smiles Back",
  "There Ain't No Party Like A ____ Party",
  "There Is A ____ On My Egg",
  "There is no Sore it will Not Heal, No ____ it will not Subdue",
  "There's Always Room For ____",
  "There's First Love, and There's ____ Love",
  "There's More Than One Way To Eat A ____",
  "There's Only One ____",
  "There's no Wrong Way to Eat a ____",
  "They Drink ____ In The Congo",
  "They're Waffly ____",
  "They're Yummy For Your ____",
  "Things Go Better with ____",
  "Things Happen After a ____",
  "Think Once, Think Twice, Think ____",
  "Think ____",
  "This Is Not Your Father's ____",
  "This Is The Age Of The ____",
  "Time To Make The ____",
  "Time for a Sharp ____",
  "To Our Members, We're The Fourth ____",
  "To Our Members, We're the Fourth Emergency ____",
  "Today's ____, Since 1903",
  "Tonight, Let It Be ____",
  "Too Orangey for ____",
  "Top Breeders Recommend ____",
  "Tough on Dirt, Gentle on ____",
  "Try ____, You'll Like It",
  "Turn Loose The ____",
  "Two Hours of ____ in Just Two Calories",
  "Uh-oh, Better Get ____",
  "Unzip a ____",
  "Vorsprung Durch ____",
  "Wait Till We Get Our ____ On You",
  "Washing Machines Live Longer With ____",
  "Watch Out, There's a ____ About",
  "We All Adore a ____",
  "We Bring The Good ____ To Life",
  "We Bring ____ to Life",
  "We Build ____",
  "We Do ____ Right",
  "We Don't Make ____. We Make ____ Better",
  "We Want To Be Smiths ____",
  "We'll Leave The ____ On For You",
  "We're Always Low ____",
  "We're Serious About ____",
  "We're with the ____",
  "Wear ____",
  "Welcome To ____ Country",
  "What Can ____ Do For You",
  "What Would You Do For A ____",
  "What's In Your ____",
  "Whatever You're Into, Get Into ____",
  "When It Absolutely, Positively Has To Be ____ Overnight",
  "When The Going Gets Tough, The Tough Get ____",
  "When You're At ____, You Feel Right At Home",
  "When You've Got ____, Flaunt It",
  "Whenever There's a Snack Gap, ____ Fits",
  "Where Do You Want ____ To Go Today",
  "Where ____ is a Pleasure",
  "Where's The ____",
  "Which Twin has the ____",
  "Who Would You Have A ____ With",
  "Why Can't Everything Orange Be ____",
  "Why Have Cotton When You Can Have ____",
  "With A Name Like ____, It Has To Be Good",
  "Would You Give Someone Your Last ____",
  "Wouldn't You Like To Be A ____ Too",
  "Wouldn't You Rather Be ____",
  "Wow! I Could Have Had a ____",
  "Yo Quiero ____",
  "You Can Be Sure of ____",
  "You Can Do It When You ____ It",
  "You Can On a ____, Can Do",
  "You Can Really Taste The ____",
  "You Can Rely On The ____",
  "You Can't Get Quicker Than a ____ Fitter",
  "You Can't Top a ____",
  "You Deserve A ____ Today",
  "You Like ____. ____ Likes You",
  "You Need A ____",
  "You Press the ____, We Do the Rest",
  "You Too Can Have A ____ Like Mine",
  "You'll Look a Little Lovelier Each Day with Fabulous Pink ____",
  "You'll Never Put A Better Bit Of ____ On Your Knife",
  "You'll Wonder Where the Yellow Went, When You Brush Your Teeth with ____",
  "You're Never Alone with a ____",
  "You're in Good Hands with ____",
  "You've Always Got Time For ____",
  "You've Got A Lot To Live, And ____'s Got A Lot To Give",
  "You've Got Questions. We've Got ____",
  "Your Flexible ____",
  "Your ____, Right Away",
  "____ - Australian for Beer",
  "____ - It Does a Body Good",
  "____ - It Looks Good on You",
  "____ - It's In The Game",
  "____ - The Appetizer",
  "____ - The Freshmaker",
  "____ - Who Could Ask For Anything More?",
  "____ Born and Bred",
  "____ Comes to Those Who Wait",
  "____ Fit For Royalty, But Affordable For All!",
  "____ Is Good For You",
  "____ Is Job 1",
  "____ Is Our Middle Name",
  "____ Is Real",
  "____ Just Feels Right",
  "____ Keeps Going and Going",
  "____ Makes Everything Better",
  "____ Not Included",
  "____ Prevents That Sinking Feeling",
  "____ Really Satisfies",
  "____ Saves Your Soul",
  "____ Serves The World",
  "____ Stays Sharp 'til The Bottom of the Glass",
  "____ Tested, Mother Approved",
  "____ Unscripted",
  "____ Wanted",
  "____ is What We Do",
  "____ is so Bracing",
  "____ with the Less Fattening Centres",
  "____, Take Me Away",
  "____, and on, and on..",
  "____-Lickin' Good",
  "____. It's Everywhere You Wanna Be",
  "____. It's What's For Dinner",
  "____: The Other White Meat"
  ];

function randomSlogan(){
  var randomSloganIndex = parseInt((listOfSlogans.length - 1) * Math.random());
  return listOfSlogans[randomSloganIndex];
}
String.prototype.capitalize = function() {
    return this.charAt(0).toUpperCase() + this.slice(1);
}

var request = require('request'),
  entities = require('./lib/entities'),
  fs = require('fs');

listen(regexFactory.startsWith(["slogan","pro","dat","them","dem","deze","that"]), function (match, data, replyTo, from) {
  var words = match[1];
  var words = words.trim();
  // while (   words.replace(/    /g, '    ').length < words.length){
  //   words = words.replace(/    /g, '    ');
  // }
  // var words = match[1].split(' ').join(' ');
  // irc.privmsg(replyTo,'-ßß¬¬¬ßsadda');
  // var words = match[1].toString('utf8');
  // words = words.replace(/\\/g, "");
  // words = words.replace(/'/g, "");
  // words = words.replace(/"/g, "");
  // words = words.replace(/`/g, "");
  // words = words.replace(/\./g, "");
  // words = words.replace(/,/g, "");
  // words = words.replace(/-/g, " ");
  //words = words.split(' ').join('%20');
  if (words === 'help' || !words) {
    irc.privmsg(replyTo,"~slogan [words] | " + listOfSlogans.length + " slogans | Original list from: thesurrealist.co.uk");
    return;
  } else {
    if (!db.hasValue(words)) db.add(words);
    words = words.capitalize();
    var slogan = randomSlogan().split('____').join(words);
    irc.privmsg(replyTo,slogan);
  }
})
