// (c) 2012 Richard Carter
// This code is licensed under the MIT license; see LICENSE.txt for details.

// This script handles the following functions:
//     slogan - make a slogan from an input

var listOfSlogans = [
"151 Countries, One __*__",
"3-in-1 Protection for your __*__",
"8 out of 10 Owners who Expressed a Preference said Their Cats Preferred __*__",
"A Day Without __*__ is Like a Day Without Sunshine",
"A Different Kind Of Company. A Different Kind Of __*__",
"A Finger of __*__ is Just Enough to Give Your Kids a Treat",
"A Glass and a Half in Every __*__",
"A Smooth-Running __*__ is a Relaxing Experience",
"A Taste For __*__",
"A Tough __*__ to Follow",
"A __*__ A Day Helps You Work, Rest and Play",
"A __*__ Is Forever",
"A __*__ Works Wonders",
"A __*__'s Too Wet Without One",
"Aaahh, __*__",
"Absolut __*__",
"All The __*__ That's Fit To Print",
"All __*__, All The Time",
"All You Add Is __*__",
"All You Need is a __*__ and a Dream",
"Always After Me __*__",
"America's Most Trusted __*__",
"An Army of __*__",
"And All Because The Lady Loves __*__",
"Any Time, Any Place, __*__",
"Ask the Man From the __*__",
"Australians Wouldn't Give A __*__ For Anything Else",
"Avez-Vous Un __*__",
"Be Like Dad, Keep __*__",
"Be Young, Have Fun, Drink __*__",
"Beanz Meanz __*__",
"Because I'm Worth __*__",
"Because So Much Is Riding On Your __*__",
"Because __*__ Can't Drive",
"Because __*__ is Complicated Enough.",
"Behold the Power of __*__",
"Bet You Can't Eat __*__",
"Better Ingredients, Better __*__",
"Better Living Through __*__",
"Beware of Expensive __*__",
"Big Chocolate __*__",
"Biting the Hand that Feeds __*__",
"Bread Wi' __*__ Taken Out",
"Break Me Off a Piece of That __*__",
"Bridge That Gap with __*__",
"Bring Out The __*__",
"Builds Bonny __*__",
"Built __*__ Tough",
"But I'd Rather Have a Bowl of __*__",
"Can You Tell __*__ From Butter",
"Can't Do It In Real Life? Do It On __*__",
"Central Heating for __*__",
"Challenge __*__",
"Change Your Whole __*__",
"Chocolate __*__ Since 1911",
"Choosy Mothers Choose __*__",
"Cleans Right Round The __*__",
"Cleans Your Floor Without __*__",
"Cleans a Big, Big __*__ For Less Than Half a Crown",
"Clunk Click, Every __*__",
"Come Fly The Friendly __*__",
"Come One, Come All To __*__",
"Come See the Softer Side of __*__",
"Come to Life.  Come to __*__",
"Come to __*__, and Let's Get It Done",
"Crunch All You Want. We'll Make __*__",
"Cuts __*__ Time in Half",
"Daddy or __*__",
"Designed for __*__",
"Designed for __*__, Engineered to Last",
"Devon Knows How They Make __*__ So Creamy",
"Dial Down the __*__",
"Did Somebody Say __*__",
"Ding-Dong! __*__ Calling",
"Discover the __*__ Difference",
"Do The __*__",
"Do You Eat The __*__ Last",
"Do You Have The __*__ Inside",
"Do You, uh, __*__",
"Does She or Doesn't She? Only Her __*__ Knows for Sure",
"Does You Does, or Does You Don't Take __*__",
"Does the Hard __*__ for You",
"Does the Hard __*__, So You Don't Have To",
"Doing It Right Before Your __*__",
"Don't Be Vague. Ask for __*__",
"Don't Forget The __*__, Mum",
"Don't Get Mad, Get __*__",
"Don't Hold __*__ Back",
"Don't Just Book It, __*__ It",
"Don't Leave Home Without __*__",
"Don't Live a Little, Live a __*__",
"Don't Say Brown, Say ",
"Don't You Just Love Being In __*__",
"Don't be an Amber __*__",
"Double the Pleasure, Double the __*__",
"Drinka Pinta __*__ A Day",
"Driven by __*__",
"Dude, You're Getting a __*__",
"Easy, Breezy, Beautiful __*__",
"Every Bubble's Passed Its __*__",
"Every Kiss Begins With __*__",
"Every __*__ Helps",
"Everyone's Favourite __*__",
"Everything We Do is Driven by __*__",
"Exceedingly Good __*__",
"Fall Into The __*__",
"Fast __*__ and Good for You",
"Feel The Raw Naked __*__ Of The Road",
"Feel the __*__",
"Fill It To The Rim With __*__",
"For Mash, Get __*__",
"For That Deep Down Body __*__",
"For The __*__ You Don't Yet Know",
"For a Hard-Earned Thirst, __*__",
"Four out of Five Dentists Recommend __*__",
"Fresh from the Captain's __*__",
"From Our __*__ to Yours",
"Full Of Eastern __*__",
"Gee, Your __*__ Smells Terrific",
"Get Back Your 'Ooo' With __*__",
"Get Busy with the __*__",
"Get In My __*__",
"Get More From __*__",
"Get Serious. Get __*__",
"Get The __*__ Out",
"Get __*__ or Get Out",
"Get the Door - It's __*__",
"Get the __*__ Habit",
"Give That Man A __*__",
"Give the Dog a __*__",
"Gives A Meal __*__-Appeal",
"Go Crack a __*__",
"Go On, Get Your __*__ Out",
"Go To Work On A __*__",
"Gonna Be a While? Grab a __*__",
"Good Honest __*__ Since 1896",
"Good To The Last __*__",
"Good __*__ Has Danish Written All Over It",
"Good to the Last __*__",
"Got __*__",
"Got a __*__? You're in Luck",
"Gotta Lotta __*__",
"Grab Life by the __*__",
"Great __*__. Great Times",
"Half the __*__, All the Taste",
"Hand-Built by __*__",
"Hands That Do Dishes Can Be Soft As Your __*__",
"Happiness is __*__-Shaped",
"Happiness is a Cigar Called __*__",
"Have __*__ Your Way",
"Have You Forgotten How Good __*__ Tastes",
"Have You Had Your __*__ Today",
"Have a Break. Have a __*__",
"Have a __*__ and Smile",
"He Who Thinks __*__ Drinks __*__",
"Ho Ho Ho, Green __*__",
"Hope It's __*__, It's __*__, We Hope It's __*__..",
"How Do You Eat <U>Your</U> __*__",
"How Many Licks Does it Take to Get to the Center of a __*__",
"How Refreshing! How __*__",
"Hungry? Why Wait? Grab a __*__",
"I Bet He Drinks __*__",
"I Can't Believe I Ate The Whole __*__",
"I Can't Believe It's Not __*__",
"I Feel Like __*__ Tonight",
"I Learned It By Watching __*__",
"I Like the __*__ in You",
"I Liked The __*__ So Much, I Bought The Company",
"I Love What You Do For __*__",
"I Saw __*__ and I Thought of You",
"I Scream, You Scream, We All Scream for __*__",
"I Think, Therefore __*__",
"I Want My __*__",
"I Was a __*__ Weakling",
"I Wish I Were a __*__ Weiner",
"I Wish They All Could Be __*__ Girls",
"I am Stuck on __*__, 'Cause __*__'s Stuck on Me",
"I'd Like to Buy the World a __*__",
"I'd Walk a Mile for a __*__",
"I'm Cuckoo For __*__",
"I'm Lovin' __*__",
"I'm Not Gonna Pay A Lot For This __*__",
"I'm Only Here For The __*__",
"I'm a Secret __*__ Drinker",
"I'm not Just the __*__, I'm a Member",
"I've Seen The Future, and It's __*__-Shaped",
"If Only Everything in Life was as Reliable as a __*__",
"If You Can't Beat __*__, Join __*__",
"If You Like A Lot Of __*__ On Your Biscuit, Join Our Club",
"If You Like A Lot of Chocolate on Your __*__, Join Our Club",
"If You Really Want To Know, Look In The __*__",
"If You Want To Get Ahead, Get A __*__",
"If You've Got the Time, We've Got the __*__",
"Is It Live, Or Is It __*__",
"Is __*__ In You",
"It Could Be __*__",
"It Does Exactly What It Says On The __*__",
"It Makes Your __*__ Smack",
"It Must Be __*__",
"It Needn't Be Hell With __*__",
"It Takes A Tough Man To Make A Tender __*__",
"It's <U>Different</U> in a __*__",
"It's A Bit Of A __*__",
"It's Good To Talk __*__",
"It's How __*__ Is Done",
"It's Just For Me And My __*__",
"It's Not All __*__, __*__, __*__, you know",
"It's Not TV. It's __*__",
"It's Shake 'n' __*__, and I Helped",
"It's Slightly Rippled with a Flat __*__",
"It's That __*__ Feeling.",
"It's __*__ Time",
"It's a Beautiful __*__",
"It's a Lot Less __*__ Than a Hover",
"It's a New __*__ Every Day",
"It's a __*__ Adventure",
"It's the Bright One, it's the Right One, that's __*__",
"It's the __*__ Fizz That Does The Bizz",
"It's the __*__ You Can See",
"Just Do __*__",
"Just Like __*__ Used To Make",
"Just One __*__ - Give It To Me",
"Just What The __*__ Ordered",
"Just for the Taste of __*__",
"Keep That __*__ Complexion",
"Kids Will Do Anything For __*__",
"Kills All Known __*__ - Dead",
"Leave the __*__ to Us",
"Leaves Your __*__ Minty not Mediciney",
"Leggo my __*__",
"Let The __*__ Take The Strain",
"Let Your Fingers Do the Walking Through the __*__",
"Let Your __*__ Do The Walking",
"Let the __*__ Begin",
"Let's Face The Music and __*__",
"Life Should Taste As Good As __*__",
"Life's Pretty Straight Without __*__",
"Lightening the __*__",
"Like __*__. Like Never Before",
"Lipsmackin' Thirstquenchin' Acetastin' Motivatin' Goodbuzzin' Cooltalkin' Highwalkin' Fastlivin' Evergivin' Coolfizzin' __*__",
"Little. Yellow. Different. __*__",
"Live in Your __*__, Play in Ours",
"Look For The __*__ Label",
"Look, Ma, No __*__",
"Loves the __*__ You Hate",
"Made In Scotland From __*__",
"Made To Make Your __*__ Water",
"Made in Scotland from __*__",
"Make Every __*__ Count",
"Make Fun of __*__",
"Make It A __*__ Night",
"Make Room for the __*__",
"Make Someone Happy with a __*__",
"Make __*__ Yours",
"Make the Most of __*__",
"Makes You Feel __*__ Again",
"Making __*__ Taste Better",
"Mama's got the Magic of __*__",
"Mamma Mia, That'sa Spicy __*__",
"Marvin the Mountie Always Gets His __*__",
"Maybe She's Born With It, Maybe It's __*__",
"Melts In Your __*__, Not In Your Hand",
"Men Can't Help Acting On __*__",
"Mild Green __*__ Liquid",
"Moms Like You Choose __*__",
"Monsieur, with this __*__ you are really spoiling us",
"More Than Just a __*__",
"More __*__ Please",
"Moving at the Speed of __*__",
"Mum's Gone to __*__",
"My Anti-Drug is __*__",
"My Doctor Says '__*__'",
"My Goodness, My __*__",
"My __*__ to Yours",
"Naughty, but __*__",
"Never Knowingly __*__",
"New Thinking. New __*__",
"Next to the Breast, __*__'s the Best",
"No __*__, No Comment",
"No-One Does Chicken Like __*__",
"Nobody Better Lay a Finger on my __*__",
"Nobody Does It Like __*__",
"Not Just Nearly __*__, But Really __*__",
"Nothin' Says Lovin' Like __*__ from the Oven",
"Nothing Acts Faster Than __*__",
"Nothing Comes Between Me And My __*__",
"Nothing Sucks Like A __*__",
"Nothing Works Better Than a __*__",
"Now with 50% more __*__",
"Obey Your __*__",
"Oh Hungry? Oh __*__",
"Once Driven, Forever __*__",
"Once You Pop, You Can't Stop __*__",
"Only The Crumbliest Flakiest __*__.",
"Only __*__ Can Prevent Forest Fires",
"Only __*__ Has The Answer",
"Only a Fool Breaks the __*__",
"Out Of The Strong Came Forth __*__",
"P-P-P-Pick Up A __*__",
"Pardon Me, Do You Have Any Grey __*__",
"Please Don't Squeeze The __*__",
"Pleasing __*__ the World Over",
"Plink, Plink, __*__..",
"Plop, Plop, Fizz, Fizz, Oh, What a __*__ it is",
"Poppin' Fresh __*__",
"Power For Your __*__",
"Prepare To Want __*__",
"Pride of the __*__ For Over a Hundred Years",
"Probably The Best __*__ In The World",
"Prolongs Active __*__",
"Promise Her Anything, But Give Her __*__",
"Pure __*__",
"Put A __*__ In Your Tank",
"Puts the __*__ in Britain",
"Race for the __*__",
"Reach Out and Touch __*__",
"Reach for the __*__",
"Recommended By Dr. __*__",
"Refreshes the __*__ Other Beers Cannot Reach",
"Ribbed For Her __*__",
"Ring Around the __*__ Gets Your Whole Wash Clean",
"Run For The __*__",
"Savour the Flavour of __*__",
"Say It With __*__",
"Schhh... You Know __*__",
"See the Face You Love Light Up With __*__",
"See the USA in Your __*__",
"See the __*__, Feel the Shine",
"Semper __*__",
"Shake the Bottle, Wake the __*__",
"Sharing the __*__ of your Life",
"Show Me The __*__",
"Silly Rabbit, __*__ is for Kids",
"Simple Impartial __*__",
"Smart. Beautiful. __*__",
"Snap Into A Slim __*__",
"Snap into a __*__",
"Snap! Crackle! __*__",
"So Easy, No Wonder __*__ is #1",
"Solutions For a Small __*__",
"Something Special In The __*__",
"Sometimes You Feel Like a __*__, Sometimes You Don't",
"Splash __*__ All Over",
"Spreads Straight from the __*__",
"Step Into The __*__",
"Stimulation for Body and __*__",
"Stop! This __*__ is not Ready Yet",
"Stop. Go. __*__",
"Strong Enough for a Man, Made for a __*__",
"Strong and Beautiful, Just Like __*__",
"Super __*__ is Almost Here",
"Sweet as the Moment When the __*__ Went ",
"Take Two Bottles into the __*__",
"Takes a __*__ but it Keeps on Tickin'",
"Taste the __*__",
"Tastes Great, Less __*__",
"Tell Them About The __*__, Mummy",
"Tense, Nervous, __*__",
"Thank __*__ It's Friday",
"That'll be the __*__",
"That's Handy, Harry! Stick It In The __*__",
"The Appliance of __*__",
"The Best Part of Waking Up is __*__ in Your Cup",
"The Best __*__ A Man Can Get",
"The Best __*__ Under One Roof",
"The Better Way to Start the __*__",
"The Biggest __*__ Pennies Can Buy",
"The Cookie That Thinks It's a __*__",
"The Coolest __*__ on Ice",
"The Cream of __*__",
"The Curiously Strong __*__",
"The Dirt says Hot, The Label says __*__",
"The Future's Bright. The Future's __*__",
"The Good __*__ Kids Go For",
"The Home of __*__",
"The Incredible, Edible __*__",
"The Joy of __*__",
"The Lighter Way To Enjoy __*__",
"The Lion Goes from __*__ to __*__",
"The Loudest Noise Comes From The Electric __*__",
"The Man From __*__, he says ",
"The Most Interesting __*__ in the World",
"The Non-Sticky Sticky __*__",
"The Passionate Pursuit of __*__",
"The Queen of __*__",
"The Real Smell of __*__",
"The Right __*__ at the Right Time",
"The Science Of __*__",
"The Sweet You Can Eat Between Meals Without Ruining Your __*__",
"The Sweet You Can't Eat Without __*__",
"The Too Good to Hurry __*__",
"The Ultimate __*__ Machine",
"The World's Favourite __*__",
"The World's Local __*__",
"The World's __*__ Marketplace",
"The __*__ Bars Are On Me",
"The __*__ Breakfast",
"The __*__ Drinker's Lighter __*__",
"The __*__ Effect",
"The __*__ For All Ages",
"The __*__ Goes Straight to your Head",
"The __*__ Of A New Generation",
"The __*__ Of Paradise",
"The __*__ Sign Means Happy Motoring",
"The __*__ That Eats Like A Meal",
"The __*__ That Likes To Say Yes",
"The __*__ That Refreshes",
"The __*__ With The Hole",
"The __*__ is Mightier than the Sword",
"The __*__ of Champions",
"The __*__ of Confidence",
"The __*__ of your Life",
"The __*__ that Smiles Back",
"There Ain't No Party Like A __*__ Party",
"There is no Sore it will Not Heal, No __*__ it will not Subdue",
"There's Always Room For __*__",
"There's First Love, and There's __*__ Love",
"There's More Than One Way To Eat A __*__",
"There's Only One __*__",
"There's no Wrong Way to Eat a __*__",
"They Drink __*__ In The Congo",
"They're Waffly __*__",
"They're Yummy For Your __*__",
"Things Go Better with __*__",
"Things Happen After a __*__",
"Think Once, Think Twice, Think __*__",
"Think __*__",
"This Is Not Your Father's __*__",
"This Is The Age Of The __*__",
"Time To Make The __*__",
"Time for a Sharp __*__",
"To Our Members, We're The Fourth __*__",
"To Our Members, We're the Fourth Emergency __*__",
"Today's __*__, Since 1903",
"Tonight, Let It Be __*__",
"Too Orangey for __*__",
"Top Breeders Recommend __*__",
"Tough on Dirt, Gentle on __*__",
"Try __*__, You'll Like It",
"Turn Loose The __*__",
"Two Hours of __*__ in Just Two Calories",
"Uh-oh, Better Get __*__",
"Unzip a __*__",
"Vorsprung Durch __*__",
"Wait Till We Get Our __*__ On You",
"Washing Machines Live Longer With __*__",
"Watch Out, There's a __*__ About",
"We All Adore a __*__",
"We Bring The Good __*__ To Life",
"We Bring __*__ to Life",
"We Build __*__",
"We Do __*__ Right",
"We Don't Make __*__. We Make __*__ Better",
"We Want To Be Smiths __*__",
"We'll Leave The __*__ On For You",
"We're Always Low __*__",
"We're Serious About __*__",
"We're with the __*__",
"Wear __*__",
"Welcome To __*__ Country",
"What Can __*__ Do For You",
"What Would You Do For A __*__",
"What's In Your __*__",
"Whatever You're Into, Get Into __*__",
"When It Absolutely, Positively Has To Be __*__ Overnight",
"When The Going Gets Tough, The Tough Get __*__",
"When You've Got __*__, Flaunt It",
"Whenever There's a Snack Gap, __*__ Fits",
"Where Do You Want __*__ To Go Today",
"Where __*__ is a Pleasure",
"Where's The __*__",
"Which Twin has the __*__",
"Who Would You Have A __*__ With",
"Why Can't Everything Orange Be __*__",
"Why Have Cotton When You Can Have __*__",
"With A Name Like __*__, It Has To Be Good",
"Would You Give Someone Your Last __*__",
"Wouldn't You Like To Be A __*__ Too",
"Wouldn't You Rather Be __*__",
"Wow! I Could Have Had a __*__",
"__*__ - Australian for Beer",
"__*__ - It Does a Body Good",
"__*__ - It Looks Good on You",
"__*__ - The Appetizer",
"__*__ - The Freshmaker",
"__*__ Born and Bred",
"__*__ Comes to Those Who Wait",
"__*__ Is Good For You",
"__*__ Is Job 1",
"__*__ Is Our Middle Name",
"__*__ Just Feels Right",
"__*__ Keeps Going and Going",
"__*__ Makes Everything Better",
"__*__ Not Included",
"__*__ Prevents That Sinking Feeling",
"__*__ Really Satisfies",
"__*__ Saves Your Soul",
"__*__ Stays Sharp 'til The Bottom of the Glass",
"__*__ Tested, Mother Approved",
"__*__ Unscripted",
"__*__ Wanted",
"__*__ is What We Do",
"__*__ is so Bracing",
"__*__ with the Less Fattening Centres",
"__*__, Take Me Away",
"__*__, and on, and on..",
"__*__-Lickin' Good",
"__*__. It's Everywhere You Wanna Be",
"__*__. It's What's For Dinner",
"__*__: The Other White Meat",
"Yo Quiero __*__",
"You Can Be Sure of __*__",
"You Can Do It When You __*__ It",
"You Can On a __*__, Can Do",
"You Can Really Taste The __*__",
"You Can't Get Quicker Than a __*__ Fitter",
"You Can't Top a __*__",
"You Deserve A __*__ Today",
"You Like __*__. __*__ Likes You",
"You Need A __*__",
"You Press the __*__, We Do the Rest",
"You Too Can Have A __*__ Like Mine",
"You'll Look a Little Lovelier Each Day with Fabulous Pink __*__",
"You'll Never Put A Better Bit Of __*__ On Your Knife",
"You'll Wonder Where the Yellow Went, When You Brush Your Teeth with __*__",
"You're Never Alone with a __*__",
"You're in Good Hands with __*__",
"You've Always Got Time For __*__",
"You've Got Questions. We've Got __*__",
"Your Flexible __*__",
"Your __*__, Right Away"
];


function randomSlogan(){
  var randomSloganIndex = parseInt((listOfSlogans.length - 1) * Math.random());
  return listOfSlogans[randomSloganIndex];
}
String.prototype.capitalize = function() {
    return this.charAt(0).toUpperCase() + this.slice(1);
}

var request = require('request'),
  entities = require('./lib/entities'),
  fs = require('fs');

listen(regexFactory.startsWith(["slogan"]), function (match, data, replyTo, from) {
  var words = match[1];
  var words = words.trim();
  // while (   words.replace(/    /g, '    ').length < words.length){
  //   words = words.replace(/    /g, '    ');
  // }
  // var words = match[1].split(' ').join(' ');
  // irc.privmsg(replyTo,'-ßß¬¬¬ßsadda');
  // var words = match[1].toString('utf8');
  // words = words.replace(/\\/g, "");
  // words = words.replace(/'/g, "");
  // words = words.replace(/"/g, "");
  // words = words.replace(/`/g, "");
  // words = words.replace(/\./g, "");
  // words = words.replace(/,/g, "");
  // words = words.replace(/-/g, " ");
  //words = words.split(' ').join('%20');
  if (words === 'help' || !words) {
    irc.privmsg(replyTo,"~slogan [words] | " + listOfSlogans.length + " slogans | Original list from: thesurrealist.co.uk");
    return;
  } else {
    words = words.capitalize();
    var slogan = randomSlogan().split('__*__').join(words);
    irc.privmsg(replyTo,slogan); 
  }
})